# Change these first
owner: El-Paso-Community-College # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: EPCC Public Website
    url: https://www.epcc.edu/pages/proxy.aspx
    maxResponseTime: 1500
  - name: MyEPCC
    url: https://my.epcc.edu
    maxResponseTime: 1500
    expectedStatusCodes:
      - 200
      - 201
      - 401
  - name: Self Service Banner
    url: https://ssb3.epcc.edu:8444/StudentRegistrationSsb
    maxResponseTime: 5000
  - name: Apps
    url: https://apps.epcc.edu
  - name: WAT
    url: https://wat.epcc.edu
  - name: ID Card Portal
    url: https://idcard.epcc.edu    
  - name: TouchNet
    url: https://secure.touchnet.com/C20715_tsa/web    
  - name: Start
    url: https://start.epcc.edu/paciweb
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.epcc.edu
  baseUrl: /upptime
  logoUrl: https://www.epcc.edu/style%20library/epcc/images/epcc_logo_white.svg
  name: Status
  introTitle: "uptime monitor and status page"
  introMessage: "INTRO MESSAGE"
  navbar:
    - title: Status
      href: /upptime
  theme: night

i18n:
  footer: "FOOTER"

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
